// Generated by cpp_rust_transpiler (C++ → Rust)

pub struct Solution {
}

impl Solution {
    fn countKthRoots(&self, l: i64, r: i64, k: i64) -> i64 {
        if (k == 1) {
            return ((r - l) + 1);
        };
        let mut cnt: i64 = 0;
        {
            let mut i: i64 = 0;
            loop {
                let mut x: i64 = 1;
                {
                    let mut j: i64 = 0;
                    while (j < k) {
                        (x *= i);
                        if (x > r) {
                            break;
                        };
                        (j += 1);
                    };
                }
                if (x > r) {
                    break;
                };
                if (x >= l) {
                    (cnt += 1);
                };
                (i += 1);
            };
        }
        return cnt;
    }
}

