use cpp_rust_transpiler::{transpile, Direction};

#[test]
fn test_cli_args_parsing() {
    // This is a smoke test ensuring the library compiles and basic API works.
    // Replace with real tests once parsers are implemented.
}

#[test]
fn test_cpp_parser_stub() {
    let source = "int main() { return 0; }";
    let ir = cpp_rust_transpiler::parser::cpp::parse(source).unwrap();
    assert_eq!(ir.items.len(), 1);
    assert!(matches!(ir.items[0], cpp_rust_transpiler::ir::Item::Function(_)));
}

#[test]
fn test_rust_parser_stub() {
    let source = "fn main() {}";
    let ir = cpp_rust_transpiler::parser::rust::parse(source).unwrap();
    assert_eq!(ir.items.len(), 1);
    assert!(matches!(ir.items[0], cpp_rust_transpiler::ir::Item::TODOComment(_)));
}

#[test]
fn test_cpp_type_mapping() {
    use cpp_rust_transpiler::ir::{Mutability, Type};
    use cpp_rust_transpiler::parser::cpp::cpp_type_to_ir;

    assert_eq!(cpp_type_to_ir("void").unwrap(), Type::Unit);
    assert_eq!(
        cpp_type_to_ir("std::vector<int>").unwrap(),
        Type::Named("Vec".to_string(), vec![Type::Named("int".to_string(), vec![])])
    );
    assert_eq!(
        cpp_type_to_ir("const int&").unwrap(),
        Type::Ref(
            Box::new(Type::Named("int".to_string(), vec![])),
            Mutability::Not
        )
    );
}

#[test]
fn test_rust_type_mapping() {
    use cpp_rust_transpiler::ir::{Mutability, Type};
    use cpp_rust_transpiler::parser::rust::rust_type_to_ir;

    assert_eq!(rust_type_to_ir("()").unwrap(), Type::Unit);
    assert_eq!(
        rust_type_to_ir("Vec<i32>").unwrap(),
        Type::Named("Vec".to_string(), vec![Type::Named("i32".to_string(), vec![])])
    );
    assert_eq!(
        rust_type_to_ir("&mut i32").unwrap(),
        Type::Ref(
            Box::new(Type::Named("i32".to_string(), vec![])),
            Mutability::Mut
        )
    );
}

#[test]
fn test_full_pipeline_cpp_to_rust() {
    let source = "int main() { return 0; }";
    let result = transpile(source, Direction::CppToRust);
    assert!(result.is_ok());
    let output = result.unwrap();
    assert!(output.contains("Generated by cpp_rust_transpiler"));
}

#[test]
fn test_full_pipeline_rust_to_cpp_stub() {
    let source = "fn main() {}";
    let result = transpile(source, Direction::RustToCpp);
    assert!(result.is_ok());
    let output = result.unwrap();
    assert!(output.contains("Generated by cpp_rust_transpiler"));
}

#[test]
fn test_template_function_parsing() {
    let source = "template <typename T> T max(T a, T b) { return a > b ? a : b; }";
    let ir = cpp_rust_transpiler::parser::cpp::parse(source).unwrap();
    assert_eq!(ir.items.len(), 1);
    match &ir.items[0] {
        cpp_rust_transpiler::ir::Item::Function(f) => {
            assert_eq!(f.name, "max");
            assert_eq!(f.generics.len(), 1);
            assert_eq!(f.generics[0].name, "T");
        }
        _ => panic!("expected Function"),
    }
}

#[test]
fn test_template_class_parsing() {
    let source = "template <typename T> class Box { public: T value; };";
    let ir = cpp_rust_transpiler::parser::cpp::parse(source).unwrap();
    assert_eq!(ir.items.len(), 1);
    match &ir.items[0] {
        cpp_rust_transpiler::ir::Item::Struct(s) => {
            assert_eq!(s.name, "Box");
            assert_eq!(s.generics.len(), 1);
            assert_eq!(s.generics[0].name, "T");
        }
        _ => panic!("expected Struct"),
    }
}

#[test]
fn test_namespace_unwrapping() {
    let source = "namespace math { int add(int a, int b) { return a + b; } }";
    let ir = cpp_rust_transpiler::parser::cpp::parse(source).unwrap();
    assert!(!ir.items.is_empty());
    match &ir.items[0] {
        cpp_rust_transpiler::ir::Item::Function(f) => {
            assert_eq!(f.name, "add");
        }
        _ => panic!("expected Function, got: {:?}", ir.items[0]),
    }
}

#[test]
fn test_generic_type_parsing() {
    use cpp_rust_transpiler::parser::cpp::cpp_type_to_ir;
    use cpp_rust_transpiler::ir::Type;

    // queue<int> should parse as Named("Queue", [Named("int", [])])
    let t = cpp_type_to_ir("queue<int>").unwrap();
    assert_eq!(
        t,
        Type::Named("Queue".to_string(), vec![Type::Named("int".to_string(), vec![])])
    );

    // map<int, string> should parse generically (string maps to String)
    let t = cpp_type_to_ir("map<int, string>").unwrap();
    assert_eq!(
        t,
        Type::Named("map".to_string(), vec![
            Type::Named("int".to_string(), vec![]),
            Type::Named("String".to_string(), vec![]),
        ])
    );

    // Verify int maps to i64 in pipeline
    assert_eq!(
        cpp_type_to_ir("int").unwrap(),
        Type::Named("int".to_string(), vec![])
    );
}

#[test]
fn test_pipeline_template_function() {
    let source = "template <typename T> T max(T a, T b) { return a > b ? a : b; }";
    let result = transpile(source, Direction::CppToRust).unwrap();
    assert!(result.contains("fn max<T>"));
    assert!(result.contains("a: T"));
    assert!(result.contains("b: T"));
    assert!(result.contains("-> T"));
}

#[test]
fn test_pipeline_decl_with_vector() {
    let source = "void f() { vector<int> order; queue<int> q; }";
    let result = transpile(source, Direction::CppToRust).unwrap();
    assert!(result.contains("Vec<i32>"));
    assert!(result.contains("VecDeque<i32>"));
}

#[test]
fn test_virtual_method_detection() {
    let source = "class A { public: virtual void f() {} };";
    let ir = cpp_rust_transpiler::parser::cpp::parse(source).unwrap();
    assert_eq!(ir.items.len(), 1);
    match &ir.items[0] {
        cpp_rust_transpiler::ir::Item::Struct(s) => {
            assert!(!s.methods.is_empty());
            assert!(s.methods[0].is_virtual);
        }
        _ => panic!("expected Struct"),
    }
}

#[test]
fn test_inheritance_parsing() {
    let source = "class Dog : public Animal { public: void bark() {} };";
    let ir = cpp_rust_transpiler::parser::cpp::parse(source).unwrap();
    match &ir.items[0] {
        cpp_rust_transpiler::ir::Item::Struct(s) => {
            assert_eq!(s.base_classes.len(), 1);
            assert_eq!(s.name, "Dog");
        }
        _ => panic!("expected Struct"),
    }
}

#[test]
fn test_alias_declaration() {
    let source = "using MyInt = int;";
    let ir = cpp_rust_transpiler::parser::cpp::parse(source).unwrap();
    assert_eq!(ir.items.len(), 1);
    assert!(matches!(ir.items[0], cpp_rust_transpiler::ir::Item::TypeAlias(_, _)));
}

#[test]
fn test_pipeline_virtual_to_trait() {
    let source = "class A { public: virtual void f() {} };";
    let result = transpile(source, Direction::CppToRust).unwrap();
    assert!(result.contains("trait ATrait"));
    assert!(result.contains("fn f(&self);"));
    assert!(result.contains("impl ATrait for A"));
}

#[test]
fn test_pipeline_inheritance_comment() {
    let source = "class Dog : public Animal { public: void bark() {} };";
    let result = transpile(source, Direction::CppToRust).unwrap();
    assert!(result.contains("Inheritance"));
    assert!(result.contains("Animal"));
}
