//! # C++ Code Generator
//!
//! Emits modern C++20 from the IR.
//!
//! ## Design notes
//! - `Box<T>`   → `std::unique_ptr<T>`
//! - `Rc<T>`    → `std::shared_ptr<T>`
//! - `Vec<T>`   → `std::vector<T>`
//! - `String`   → `std::string`
//! - `Option<T>`→ `std::optional<T>`
//! - `Result<T,E>`→ `std::expected<T,E>` (C++23) or custom struct for C++20
//! - `&T` / `&mut T` → `const T&` / `T&`
//! - `match`    → `std::visit` + `std::variant` or if-else chain
//! - `trait`    → `concept` + template parameter or abstract base class
//! - Lifetimes  → `// Lifetime: ...` comments
//! - `unsafe`   → Raw pointer ops with `// SAFETY: ...` comments

use crate::ir::*;
use anyhow::Result;

/// Generate C++ source from the IR.
pub fn generate(ir: &Module) -> Result<String> {
    let mut out = String::new();
    out.push_str("// Generated by cpp_rust_transpiler (Rust → C++)\n");
    out.push_str("#include <cstdint>\n");
    out.push_str("#include <string>\n");
    out.push_str("#include <vector>\n");
    out.push_str("#include <memory>\n");
    out.push_str("#include <optional>\n");
    out.push_str("#include <variant>\n");
    out.push_str("#include <utility>\n");
    out.push_str("\n");

    for item in &ir.items {
        generate_item(&mut out, item)?;
        out.push('\n');
    }

    Ok(out)
}

fn generate_item(out: &mut String, item: &Item) -> Result<()> {
    match item {
        Item::Function(f) => generate_function(out, f)?,
        Item::Struct(s) => generate_struct(out, s)?,
        Item::Enum(e) => generate_enum(out, e)?,
        Item::Trait(t) => generate_trait(out, t)?,
        Item::Impl(i) => generate_impl(out, i)?,
        Item::TypeAlias(name, ty) => {
            out.push_str("using ");
            out.push_str(name);
            out.push_str(" = ");
            generate_type(out, ty)?;
            out.push_str(";\n");
        }
        Item::Use(path) => {
            out.push_str("// using/import: ");
            out.push_str(path);
            out.push('\n');
        }
        Item::TODOComment(msg) => {
            out.push_str("// TODO: manual review needed: ");
            out.push_str(msg);
            out.push('\n');
        }
    }
    Ok(())
}

fn generate_function(out: &mut String, f: &Function) -> Result<()> {
    if f.is_unsafe {
        out.push_str("// SAFETY: This function originated from Rust `unsafe` or C++ raw pointers.\n");
    }

    // template header for generics
    if !f.generics.is_empty() {
        out.push_str("template <");
        for (i, g) in f.generics.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str("typename ");
            out.push_str(&g.name);
            for bound in &g.bounds {
                out.push_str(" /* : ");
                generate_type_inline(out, bound)?;
                out.push_str(" */");
            }
        }
        out.push_str(">\n");
    }

    if let Some(ret) = &f.ret_ty {
        generate_type(out, ret)?;
    } else {
        out.push_str("void");
    }
    out.push(' ');
    out.push_str(&f.name);
    out.push('(');
    for (i, p) in f.params.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        generate_type(out, &p.ty)?;
        out.push(' ');
        out.push_str(&p.name);
    }
    out.push_str(") {\n");
    generate_block(out, &f.body, 1)?;
    out.push_str("}\n");
    Ok(())
}

fn generate_struct(out: &mut String, s: &StructDef) -> Result<()> {
    let keyword = if s.is_class { "class" } else { "struct" };
    out.push_str(keyword);
    out.push(' ');
    out.push_str(&s.name);
    if !s.generics.is_empty() {
        out.push_str("<");
        for (i, g) in s.generics.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str("typename ");
            out.push_str(&g.name);
        }
        out.push_str(">");
    }
    out.push_str(" {\n");
    if s.is_class {
        out.push_str("public:\n");
    }
    for field in &s.fields {
        out.push_str("    ");
        generate_type(out, &field.ty)?;
        out.push(' ');
        out.push_str(&field.name);
        out.push_str(";\n");
    }
    out.push_str("};\n");
    Ok(())
}

fn generate_enum(out: &mut String, e: &EnumDef) -> Result<()> {
    // Rust enum -> std::variant (MVP: only simple enums)
    out.push_str("// TODO: manual review needed: Rust enum mapped to std::variant\n");
    out.push_str("using ");
    out.push_str(&e.name);
    out.push_str(" = std::variant<");
    for (i, v) in e.variants.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        match &v.fields {
            VariantFields::Unit => out.push_str("std::monostate"),
            VariantFields::Tuple(types) => {
                out.push_str("std::tuple<");
                for (j, t) in types.iter().enumerate() {
                    if j > 0 {
                        out.push_str(", ");
                    }
                    generate_type_inline(out, t)?;
                }
                out.push_str(">");
            }
            VariantFields::Struct(fields) => {
                out.push_str("std::tuple<");
                for (j, f) in fields.iter().enumerate() {
                    if j > 0 {
                        out.push_str(", ");
                    }
                    generate_type_inline(out, &f.ty)?;
                }
                out.push_str(">");
            }
        }
    }
    out.push_str(">;\n");
    Ok(())
}

fn generate_trait(out: &mut String, t: &TraitDef) -> Result<()> {
    out.push_str("// TODO: manual review needed: Rust trait -> C++ concept / abstract base class\n");
    out.push_str("// trait ");
    out.push_str(&t.name);
    out.push('\n');
    for item in &t.items {
        match item {
            TraitItem::Function(f) => {
                out.push_str("// abstract method: ");
                out.push_str(&f.name);
                out.push('\n');
            }
            TraitItem::Type(name, _bounds) => {
                out.push_str("// associated type: ");
                out.push_str(name);
                out.push('\n');
            }
            TraitItem::Const(name, ty, _val) => {
                out.push_str("// const: ");
                out.push_str(name);
                out.push_str(": ");
                generate_type_inline(out, ty)?;
                out.push('\n');
            }
            TraitItem::TODOComment(msg) => {
                out.push_str("// TODO: ");
                out.push_str(msg);
                out.push('\n');
            }
        }
    }
    Ok(())
}

fn generate_impl(out: &mut String, i: &ImplBlock) -> Result<()> {
    if let Some(trait_name) = &i.trait_name {
        out.push_str("// impl ");
        out.push_str(trait_name);
        out.push_str(" for ");
        generate_type_inline(out, &i.for_type)?;
        out.push('\n');
    }
    for item in &i.items {
        match item {
            ImplItem::Function(f) => generate_function(out, f)?,
            ImplItem::Const(name, ty, val) => {
                out.push_str("constexpr ");
                generate_type_inline(out, ty)?;
                out.push(' ');
                out.push_str(name);
                if let Some(v) = val {
                    out.push_str(" = ");
                    generate_literal_inline(out, v);
                }
                out.push_str(";\n");
            }
            ImplItem::Type(name, ty) => {
                out.push_str("using ");
                out.push_str(name);
                out.push_str(" = ");
                generate_type_inline(out, ty)?;
                out.push_str(";\n");
            }
        }
    }
    Ok(())
}

fn generate_block(out: &mut String, block: &Block, indent: usize) -> Result<()> {
    let pad = "    ".repeat(indent);
    for stmt in &block.stmts {
        out.push_str(&pad);
        generate_stmt(out, stmt, indent)?;
    }
    if let Some(expr) = &block.expr {
        out.push_str(&pad);
        out.push_str("return ");
        generate_expr(out, expr, indent)?;
        out.push_str(";\n");
    }
    Ok(())
}

fn generate_stmt(out: &mut String, stmt: &Stmt, indent: usize) -> Result<()> {
    match stmt {
        Stmt::Let(l) => {
            if l.mutable {
                out.push_str("auto ");
            } else {
                out.push_str("const auto ");
            }
            out.push_str(&l.name);
            if let Some(ty) = &l.ty {
                out.push_str(" /* : ");
                generate_type_inline(out, ty)?;
                out.push_str(" */");
            }
            if let Some(init) = &l.init {
                out.push_str(" = ");
                generate_expr(out, init, indent)?;
            }
            out.push_str(";\n");
        }
        Stmt::Expr(e) => {
            generate_expr(out, e, indent)?;
            out.push_str(";\n");
        }
        Stmt::Return(e) => {
            out.push_str("return");
            if let Some(expr) = e {
                out.push(' ');
                generate_expr(out, expr, indent)?;
            }
            out.push_str(";\n");
        }
        Stmt::Assign(lhs, rhs) => {
            generate_expr(out, lhs, indent)?;
            out.push_str(" = ");
            generate_expr(out, rhs, indent)?;
            out.push_str(";\n");
        }
        Stmt::Block(b) => {
            out.push_str("{\n");
            generate_block(out, b, indent + 1)?;
            out.push_str(&"    ".repeat(indent));
            out.push_str("}\n");
        }
    }
    Ok(())
}

fn generate_expr(out: &mut String, expr: &Expr, _indent: usize) -> Result<()> {
    match expr {
        Expr::Literal(lit) => generate_literal_inline(out, lit),
        Expr::Ident(name) => out.push_str(name),
        Expr::Binary(op, lhs, rhs) => {
            out.push('(');
            generate_expr(out, lhs, _indent)?;
            out.push(' ');
            out.push_str(&op.to_string());
            out.push(' ');
            generate_expr(out, rhs, _indent)?;
            out.push(')');
        }
        Expr::Unary(op, inner) => {
            out.push_str(&op.to_string());
            generate_expr(out, inner, _indent)?;
        }
        Expr::Call(callee, args) => {
            generate_expr(out, callee, _indent)?;
            out.push('(');
            for (i, arg) in args.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                generate_expr(out, arg, _indent)?;
            }
            out.push(')');
        }
        Expr::MethodCall(receiver, method, args) => {
            generate_expr(out, receiver, _indent)?;
            out.push('.');
            out.push_str(method);
            out.push('(');
            for (i, arg) in args.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                generate_expr(out, arg, _indent)?;
            }
            out.push(')');
        }
        Expr::Field(obj, field) => {
            generate_expr(out, obj, _indent)?;
            out.push('.');
            out.push_str(field);
        }
        Expr::Index(arr, idx) => {
            generate_expr(out, arr, _indent)?;
            out.push('[');
            generate_expr(out, idx, _indent)?;
            out.push(']');
        }
        Expr::If(cond, then_branch, else_branch) => {
            out.push_str("if (");
            generate_expr(out, cond, _indent)?;
            out.push_str(") {\n");
            generate_block(out, then_branch, _indent + 1)?;
            out.push_str(&"    ".repeat(_indent));
            out.push('}');
            if let Some(else_b) = else_branch {
                out.push_str(" else {\n");
                generate_block(out, else_b, _indent + 1)?;
                out.push_str(&"    ".repeat(_indent));
                out.push('}');
            }
        }
        Expr::Match(_scrutinee, _arms) => {
            out.push_str("// TODO: manual review needed: Rust match -> std::visit or if-else chain\n");
            out.push_str(&"    ".repeat(_indent));
            out.push_str("/* match expression */");
        }
        Expr::While(cond, body) => {
            out.push_str("while (");
            generate_expr(out, cond, _indent)?;
            out.push_str(") {\n");
            generate_block(out, body, _indent + 1)?;
            out.push_str(&"    ".repeat(_indent));
            out.push('}');
        }
        Expr::For(head, body) => {
            out.push_str("for (auto&& ");
            generate_pattern_inline(out, &head.pat);
            out.push_str(" : ");
            generate_expr(out, &head.expr, _indent)?;
            out.push_str(") {\n");
            generate_block(out, body, _indent + 1)?;
            out.push_str(&"    ".repeat(_indent));
            out.push('}');
        }
        Expr::Block(block) => {
            out.push_str("{\n");
            generate_block(out, block, _indent + 1)?;
            out.push_str(&"    ".repeat(_indent));
            out.push('}');
        }
        Expr::StructInit(name, fields) => {
            out.push_str(name);
            out.push_str("{");
            for (i, (fname, fexpr)) in fields.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                out.push('.');
                out.push_str(fname);
                out.push_str(" = ");
                generate_expr(out, fexpr, _indent)?;
            }
            out.push('}');
        }
        Expr::ArrayInit(elems) => {
            out.push_str("{");
            for (i, e) in elems.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                generate_expr(out, e, _indent)?;
            }
            out.push('}');
        }
        Expr::Tuple(elems) => {
            out.push_str("std::make_tuple(");
            for (i, e) in elems.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                generate_expr(out, e, _indent)?;
            }
            out.push(')');
        }
        Expr::Break => out.push_str("break"),
        Expr::Continue => out.push_str("continue"),
        Expr::Closure(_, _, _) => {
            out.push_str("/* TODO: manual review needed: C++ lambda -> C++ lambda (round-trip not yet supported) */");
        }
        Expr::TODO(msg) => {
            out.push_str("/* TODO: ");
            out.push_str(msg);
            out.push_str(" */");
        }
    }
    Ok(())
}

fn generate_type(out: &mut String, ty: &Type) -> Result<()> {
    match ty {
        Type::Unit => out.push_str("void"),
        Type::Never => out.push_str("[[noreturn]] void"),
        Type::Infer => out.push_str("auto"),
        Type::Named(name, args) => {
            let cpp_name = map_rust_type_to_cpp(name);
            out.push_str(&cpp_name);
            if !args.is_empty() {
                out.push('<');
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 {
                        out.push_str(", ");
                    }
                    generate_type_inline(out, arg)?;
                }
                out.push('>');
            }
        }
        Type::Ref(inner, mutability) => {
            if *mutability == Mutability::Not {
                out.push_str("const ");
            }
            generate_type_inline(out, inner)?;
            out.push('&');
        }
        Type::Ptr(inner, mutability) => {
            if *mutability == Mutability::Not {
                out.push_str("const ");
            }
            generate_type_inline(out, inner)?;
            out.push('*');
        }
        Type::Array(inner, len) => {
            out.push_str("std::array<");
            generate_type_inline(out, inner)?;
            out.push_str(", ");
            if let Some(n) = len {
                out.push_str(&n.to_string());
            } else {
                out.push('?');
            }
            out.push_str(">");
        }
        Type::Tuple(elems) => {
            out.push_str("std::tuple<");
            for (i, e) in elems.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                generate_type_inline(out, e)?;
            }
            out.push('>');
        }
        Type::Function(args, ret) => {
            out.push_str("std::function<");
            generate_type_inline(out, ret)?;
            out.push('(');
            for (i, a) in args.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                generate_type_inline(out, a)?;
            }
            out.push_str(")>");
        }
        Type::Slice(inner) => {
            out.push_str("std::span<");
            generate_type_inline(out, inner)?;
            out.push('>');
        }
        Type::TODO(msg) => {
            out.push_str("/* TODO type: ");
            out.push_str(msg);
            out.push_str(" */ int");
        }
    }
    Ok(())
}

fn generate_type_inline(out: &mut String, ty: &Type) -> Result<()> {
    generate_type(out, ty)
}

fn map_rust_type_to_cpp(name: &str) -> String {
    match name {
        "Vec" => "std::vector".to_string(),
        "Box" => "std::unique_ptr".to_string(),
        "Rc" | "Arc" => "std::shared_ptr".to_string(),
        "String" => "std::string".to_string(),
        "Option" => "std::optional".to_string(),
        "Result" => "/* std::expected (C++23) */ std::variant".to_string(), // TODO: custom Result for C++20
        "HashMap" => "std::unordered_map".to_string(),
        "HashSet" => "std::unordered_set".to_string(),
        "BTreeMap" => "std::map".to_string(),
        "BTreeSet" => "std::set".to_string(),
        "bool" => "bool".to_string(),
        "char" => "char32_t".to_string(),
        "i8" => "int8_t".to_string(),
        "i16" => "int16_t".to_string(),
        "i32" => "int32_t".to_string(),
        "i64" => "int64_t".to_string(),
        "u8" => "uint8_t".to_string(),
        "u16" => "uint16_t".to_string(),
        "u32" => "uint32_t".to_string(),
        "u64" => "uint64_t".to_string(),
        "usize" => "size_t".to_string(),
        "isize" => "ptrdiff_t".to_string(),
        "f32" => "float".to_string(),
        "f64" => "double".to_string(),
        other => other.to_string(), // fallback
    }
}

fn generate_literal_inline(out: &mut String, lit: &Literal) {
    match lit {
        Literal::Int(s) => out.push_str(s),
        Literal::Float(s) => out.push_str(s),
        Literal::String(s) => {
            out.push('"');
            out.push_str(s);
            out.push('"');
        }
        Literal::Char(c) => {
            out.push('\'');
            out.push(*c);
            out.push('\'');
        }
        Literal::Bool(b) => out.push_str(if *b { "true" } else { "false" }),
    }
}

fn generate_pattern_inline(out: &mut String, pat: &Pattern) {
    match pat {
        Pattern::Wild => out.push('_'),
        Pattern::Literal(lit) => generate_literal_inline(out, lit),
        Pattern::Ident(name) => out.push_str(name),
        Pattern::Struct(name, fields) => {
            out.push_str(name);
            out.push('{');
            for (i, (fname, fpat)) in fields.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                out.push('.');
                out.push_str(fname);
                out.push_str(" = ");
                generate_pattern_inline(out, fpat);
            }
            out.push('}');
        }
        Pattern::Tuple(pats) => {
            out.push('(');
            for (i, p) in pats.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                generate_pattern_inline(out, p);
            }
            out.push(')');
        }
        Pattern::Array(pats) => {
            out.push('[');
            for (i, p) in pats.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                generate_pattern_inline(out, p);
            }
            out.push(']');
        }
        Pattern::Ref(p) => {
            out.push_str("const auto& ");
            generate_pattern_inline(out, p);
        }
        Pattern::Mut(p) => {
            out.push_str("auto& ");
            generate_pattern_inline(out, p);
        }
        Pattern::Or(pats) => {
            for (i, p) in pats.iter().enumerate() {
                if i > 0 {
                    out.push_str(" | ");
                }
                generate_pattern_inline(out, p);
            }
        }
    }
}
