//! # Rust Code Generator
//!
//! Emits idiomatic Rust from the IR.
//!
//! ## Design notes
//! - `std::unique_ptr<T>` → `Box<T>`
//! - `std::shared_ptr<T>` → `Rc<T>` / `Arc<T>`
//! - `std::vector<T>`    → `Vec<T>`
//! - `std::string`       → `String`
//! - `std::optional<T>`  → `Option<T>`
//! - `std::expected<T,E>` → `Result<T, E>`
//! - `const T&` / `T&`   → `&T` / `&mut T`
//! - `class` / `struct`  → `struct` + `impl`
//! - `virtual`           → `trait` + `dyn` (TODO)
//! - `new` / `delete`    → `Box::new` / Drop
//! - Constructors/RAII   → `Drop` trait
//! - `std::thread`       → `std::thread::spawn`
//! - Raw pointers `T*`   → `unsafe` block raw pointers or upgrade to references

use crate::ir::*;
use anyhow::Result;

/// Strip `return 0;` from main function body (Rust main returns ()).
fn strip_return_zero_block(block: &mut Block) {
    for stmt in &mut block.stmts {
        strip_return_zero_stmt(stmt);
    }
    if let Some(expr) = &mut block.expr {
        strip_return_zero_expr(expr);
    }
}

fn strip_return_zero_stmt(stmt: &mut Stmt) {
    match stmt {
        Stmt::Return(Some(expr)) => {
            if matches!(expr.as_ref(), Expr::Literal(Literal::Int(s)) if s == "0") {
                *stmt = Stmt::Return(None);
            }
        }
        Stmt::Block(b) => strip_return_zero_block(b),
        Stmt::Let(l) => {
            if let Some(init) = &mut l.init {
                strip_return_zero_expr(init);
            }
        }
        Stmt::Expr(e) => strip_return_zero_expr(e),
        Stmt::Assign(lhs, rhs) => {
            strip_return_zero_expr(lhs);
            strip_return_zero_expr(rhs);
        }
        _ => {}
    }
}

fn strip_return_zero_expr(expr: &mut Expr) {
    match expr {
        Expr::Block(b) => strip_return_zero_block(b),
        Expr::If(_, then_b, else_b) => {
            strip_return_zero_block(then_b);
            if let Some(b) = else_b {
                strip_return_zero_block(b);
            }
        }
        Expr::While(_, b) => strip_return_zero_block(b),
        Expr::For(_, b) => strip_return_zero_block(b),
        Expr::Match(_, arms) => {
            for arm in arms {
                if let Some(guard) = &mut arm.guard {
                    strip_return_zero_expr(guard);
                }
                strip_return_zero_expr(&mut arm.body);
            }
        }
        Expr::Binary(_, lhs, rhs) => {
            strip_return_zero_expr(lhs);
            strip_return_zero_expr(rhs);
        }
        Expr::Unary(_, inner) => strip_return_zero_expr(inner),
        Expr::Call(callee, args) => {
            strip_return_zero_expr(callee);
            for arg in args {
                strip_return_zero_expr(arg);
            }
        }
        Expr::MethodCall(receiver, _, args) => {
            strip_return_zero_expr(receiver);
            for arg in args {
                strip_return_zero_expr(arg);
            }
        }
        Expr::Field(obj, _) => strip_return_zero_expr(obj),
        Expr::Index(arr, idx) => {
            strip_return_zero_expr(arr);
            strip_return_zero_expr(idx);
        }
        Expr::StructInit(_, fields) => {
            for (_, fexpr) in fields {
                strip_return_zero_expr(fexpr);
            }
        }
        Expr::ArrayInit(elems) | Expr::Tuple(elems) => {
            for elem in elems {
                strip_return_zero_expr(elem);
            }
        }
        _ => {}
    }
}

/// Generate Rust source from the IR.
pub fn generate(ir: &Module) -> Result<String> {
    let mut out = String::new();
    out.push_str("// Generated by cpp_rust_transpiler (C++ → Rust)\n");
    out.push_str("\n");

    for item in &ir.items {
        generate_item(&mut out, item)?;
        out.push('\n');
    }

    Ok(out)
}

fn generate_item(out: &mut String, item: &Item) -> Result<()> {
    match item {
        Item::Function(f) => generate_function(out, f)?,
        Item::Struct(s) => generate_struct(out, s)?,
        Item::Enum(e) => generate_enum(out, e)?,
        Item::Trait(t) => generate_trait(out, t)?,
        Item::Impl(i) => generate_impl(out, i)?,
        Item::TypeAlias(name, ty) => {
            out.push_str("type ");
            out.push_str(name);
            out.push_str(" = ");
            generate_type(out, ty)?;
            out.push_str(";\n");
        }
        Item::Use(path) => {
            out.push_str("use ");
            out.push_str(path);
            out.push_str(";\n");
        }
        Item::TODOComment(msg) => {
            out.push_str("// TODO: manual review needed: ");
            out.push_str(msg);
            out.push('\n');
        }
    }
    Ok(())
}

fn generate_function(out: &mut String, f: &Function) -> Result<()> {
    let mut f = f.clone();
    let is_main = f.name == "main";
    if is_main {
        f.ret_ty = Some(Type::Unit);
        strip_return_zero_block(&mut f.body);
    }
    if f.is_unsafe {
        out.push_str("unsafe ");
    }
    out.push_str("fn ");
    out.push_str(&f.name);

    // generics
    if !f.generics.is_empty() {
        out.push('<');
        for (i, g) in f.generics.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str(&g.name);
            if !g.bounds.is_empty() {
                out.push_str(": ");
                for (j, b) in g.bounds.iter().enumerate() {
                    if j > 0 {
                        out.push_str(" + ");
                    }
                    generate_type_inline(out, b)?;
                }
            }
        }
        out.push('>');
    }

    out.push('(');
    if let Some(self_param) = &f.self_param {
        match self_param {
            SelfParam::Value => out.push_str("self"),
            SelfParam::Ref => out.push_str("&self"),
            SelfParam::MutRef => out.push_str("&mut self"),
            SelfParam::Ptr => out.push_str("*const self"),
            SelfParam::MutPtr => out.push_str("*mut self"),
        }
        if !f.params.is_empty() {
            out.push_str(", ");
        }
    }
    for (i, p) in f.params.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&p.name);
        out.push_str(": ");
        generate_type(out, &p.ty)?;
    }
    out.push(')');

    // Rust `main` must return () or Result, not i32
    let is_main = f.name == "main";
    if !is_main {
        if let Some(ret) = &f.ret_ty {
            if *ret != Type::Unit {
                out.push_str(" -> ");
                generate_type(out, ret)?;
            }
        }
    }

    out.push_str(" {\n");
    generate_block(out, &f.body, 1)?;
    out.push_str("}\n");
    Ok(())
}

fn generate_struct(out: &mut String, s: &StructDef) -> Result<()> {
    out.push_str("pub struct ");
    out.push_str(&s.name);
    if !s.generics.is_empty() {
        out.push('<');
        for (i, g) in s.generics.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str(&g.name);
        }
        out.push('>');
    }
    out.push_str(" {\n");
    for field in &s.fields {
        out.push_str("    pub ");
        out.push_str(&field.name);
        out.push_str(": ");
        generate_type(out, &field.ty)?;
        out.push_str(",\n");
    }
    out.push_str("}\n");

    // Generate impl block for methods extracted from C++ class
    if !s.methods.is_empty() {
        out.push_str("\nimpl ");
        if !s.generics.is_empty() {
            out.push('<');
            for (i, g) in s.generics.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                out.push_str(&g.name);
            }
            out.push('>');
        }
        out.push_str(&s.name);
        if !s.generics.is_empty() {
            out.push('<');
            for (i, g) in s.generics.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                out.push_str(&g.name);
            }
            out.push('>');
        }
        out.push_str(" {\n");
        for method in &s.methods {
            let mut method = method.clone();
            // C++ constructor -> Rust `new`
            if method.name == s.name {
                method.name = "new".to_string();
                method.ret_ty = Some(Type::Named("Self".to_string(), vec![]));
                method.self_param = None; // constructor is an associated function, not a method
                // Build `Self { field1, field2, ... }` assuming param names match field names
                let init_fields: Vec<(String, Expr)> = s.fields.iter()
                    .map(|f| (f.name.clone(), Expr::Ident(f.name.clone())))
                    .collect();
                method.body = Block {
                    stmts: vec![],
                    expr: Some(Box::new(Expr::StructInit("Self".to_string(), init_fields))),
                };
            }
            let mut fn_str = String::new();
            generate_function(&mut fn_str, &method)?;
            for line in fn_str.lines() {
                out.push_str("    ");
                out.push_str(line);
                out.push('\n');
            }
        }
        out.push_str("}\n");
    }
    Ok(())
}

fn generate_enum(out: &mut String, e: &EnumDef) -> Result<()> {
    out.push_str("pub enum ");
    out.push_str(&e.name);
    if !e.generics.is_empty() {
        out.push('<');
        for (i, g) in e.generics.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str(&g.name);
        }
        out.push('>');
    }
    out.push_str(" {\n");
    for variant in &e.variants {
        out.push_str("    ");
        out.push_str(&variant.name);
        match &variant.fields {
            VariantFields::Unit => {}
            VariantFields::Tuple(types) => {
                out.push('(');
                for (i, t) in types.iter().enumerate() {
                    if i > 0 {
                        out.push_str(", ");
                    }
                    generate_type_inline(out, t)?;
                }
                out.push(')');
            }
            VariantFields::Struct(fields) => {
                out.push_str(" {\n");
                for f in fields {
                    out.push_str("        ");
                    out.push_str(&f.name);
                    out.push_str(": ");
                    generate_type_inline(out, &f.ty)?;
                    out.push_str(",\n");
                }
                out.push_str("    }");
            }
        }
        out.push_str(",\n");
    }
    out.push_str("}\n");
    Ok(())
}

fn generate_trait(out: &mut String, t: &TraitDef) -> Result<()> {
    out.push_str("pub trait ");
    out.push_str(&t.name);
    if !t.generics.is_empty() {
        out.push('<');
        for (i, g) in t.generics.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str(&g.name);
        }
        out.push('>');
    }
    out.push_str(" {\n");
    for item in &t.items {
        match item {
            TraitItem::Function(f) => {
                out.push_str("    fn ");
                out.push_str(&f.name);
                out.push('(');
                for (i, p) in f.params.iter().enumerate() {
                    if i > 0 {
                        out.push_str(", ");
                    }
                    out.push_str(&p.name);
                    out.push_str(": ");
                    generate_type_inline(out, &p.ty)?;
                }
                out.push(')');
                if let Some(ret) = &f.ret_ty {
                    out.push_str(" -> ");
                    generate_type_inline(out, ret)?;
                }
                out.push_str(";\n");
            }
            TraitItem::Type(name, bounds) => {
                out.push_str("    type ");
                out.push_str(name);
                if !bounds.is_empty() {
                    out.push_str(": ");
                    for (i, b) in bounds.iter().enumerate() {
                        if i > 0 {
                            out.push_str(" + ");
                        }
                        generate_type_inline(out, b)?;
                    }
                }
                out.push_str(";\n");
            }
            TraitItem::Const(name, ty, val) => {
                out.push_str("    const ");
                out.push_str(name);
                out.push_str(": ");
                generate_type_inline(out, ty)?;
                if let Some(v) = val {
                    out.push_str(" = ");
                    generate_literal_inline(out, v);
                }
                out.push_str(";\n");
            }
            TraitItem::TODOComment(msg) => {
                out.push_str("    // TODO: ");
                out.push_str(msg);
                out.push('\n');
            }
        }
    }
    out.push_str("}\n");
    Ok(())
}

fn generate_impl(out: &mut String, i: &ImplBlock) -> Result<()> {
    out.push_str("impl");
    if !i.generics.is_empty() {
        out.push('<');
        for (j, g) in i.generics.iter().enumerate() {
            if j > 0 {
                out.push_str(", ");
            }
            out.push_str(&g.name);
        }
        out.push('>');
    }
    if let Some(trait_name) = &i.trait_name {
        out.push(' ');
        out.push_str(trait_name);
        out.push_str(" for ");
    } else {
        out.push(' ');
    }
    generate_type_inline(out, &i.for_type)?;
    out.push_str(" {\n");
    for item in &i.items {
        match item {
            ImplItem::Function(f) => {
                // Indent function body
                let mut fn_str = String::new();
                generate_function(&mut fn_str, f)?;
                for line in fn_str.lines() {
                    out.push_str("    ");
                    out.push_str(line);
                    out.push('\n');
                }
            }
            ImplItem::Const(name, ty, val) => {
                out.push_str("    const ");
                out.push_str(name);
                out.push_str(": ");
                generate_type_inline(out, ty)?;
                if let Some(v) = val {
                    out.push_str(" = ");
                    generate_literal_inline(out, v);
                }
                out.push_str(";\n");
            }
            ImplItem::Type(name, ty) => {
                out.push_str("    type ");
                out.push_str(name);
                out.push_str(" = ");
                generate_type_inline(out, ty)?;
                out.push_str(";\n");
            }
        }
    }
    out.push_str("}\n");
    Ok(())
}

fn generate_block(out: &mut String, block: &Block, indent: usize) -> Result<()> {
    let pad = "    ".repeat(indent);
    for stmt in &block.stmts {
        out.push_str(&pad);
        generate_stmt(out, stmt, indent)?;
    }
    if let Some(expr) = &block.expr {
        out.push_str(&pad);
        generate_expr(out, expr, indent)?;
        out.push('\n');
    }
    Ok(())
}

fn generate_stmt(out: &mut String, stmt: &Stmt, indent: usize) -> Result<()> {
    match stmt {
        Stmt::Let(l) => {
            out.push_str("let ");
            if l.mutable {
                out.push_str("mut ");
            }
            generate_pattern_inline(out, &Pattern::Ident(l.name.clone()))?;
            if let Some(ty) = &l.ty {
                out.push_str(": ");
                generate_type_inline(out, ty)?;
            }
            if let Some(init) = &l.init {
                out.push_str(" = ");
                if is_vec_array_init(&l.ty, init) {
                    out.push_str("vec!");
                    if let Expr::ArrayInit(elems) = init.as_ref() {
                        out.push('[');
                        for (i, e) in elems.iter().enumerate() {
                            if i > 0 {
                                out.push_str(", ");
                            }
                            generate_expr(out, e, indent)?;
                        }
                        out.push(']');
                    } else {
                        generate_expr(out, init, indent)?;
                    }
                } else if is_vec_constructor(&l.ty, init) {
                    if let Expr::Call(_, args) = init.as_ref() {
                        match args.len() {
                            0 => out.push_str("Vec::new()"),
                            1 => {
                                out.push_str("Vec::with_capacity(");
                                generate_expr(out, &args[0], indent)?;
                                out.push(')');
                            }
                            2 => {
                                out.push_str("vec![");
                                generate_expr(out, &args[1], indent)?;
                                out.push_str("; ");
                                generate_expr(out, &args[0], indent)?;
                                out.push(']');
                            }
                            _ => generate_expr(out, init, indent)?,
                        }
                    } else {
                        generate_expr(out, init, indent)?;
                    }
                } else if is_string_init(&l.ty, init) {
                    out.push_str("String::from(");
                    generate_expr(out, init, indent)?;
                    out.push(')');
                } else {
                    generate_expr(out, init, indent)?;
                }
            }
            out.push_str(";\n");
        }
        Stmt::Expr(e) => {
            generate_expr(out, e, indent)?;
            out.push_str(";\n");
        }
        Stmt::Return(e) => {
            out.push_str("return");
            if let Some(expr) = e {
                if matches!(expr.as_ref(), Expr::ArrayInit(v) if v.is_empty()) {
                    out.push_str(" Vec::new()");
                } else {
                    out.push(' ');
                    generate_expr(out, expr, indent)?;
                }
            }
            out.push_str(";\n");
        }
        Stmt::Assign(lhs, rhs) => {
            generate_expr(out, lhs, indent)?;
            out.push_str(" = ");
            generate_expr(out, rhs, indent)?;
            out.push_str(";\n");
        }
        Stmt::Block(b) => {
            out.push_str("{\n");
            generate_block(out, b, indent + 1)?;
            out.push_str(&"    ".repeat(indent));
            out.push_str("}\n");
        }
    }
    Ok(())
}

/// Check if this is a `Vec<T>` initialized with an array literal.
fn is_vec_array_init(ty: &Option<Type>, init: &Expr) -> bool {
    matches!(
        (ty, init),
        (Some(Type::Named(name, _)), Expr::ArrayInit(_)) if name == "Vec"
    )
}

/// Check if this is a `Vec<T>` initialized via constructor call (e.g. vector(k, val)).
fn is_vec_constructor(ty: &Option<Type>, init: &Expr) -> bool {
    matches!(
        (ty, init),
        (Some(Type::Named(name, _)), Expr::Call(_, _)) if name == "Vec" || name == "vector"
    )
}

/// Check if this is a `String` initialized with a string literal.
fn is_string_init(ty: &Option<Type>, init: &Expr) -> bool {
    matches!(
        (ty, init),
        (Some(Type::Named(name, _)), Expr::Literal(Literal::String(_))) if name == "String" || name == "string"
    )
}

/// Collect all operands in a chain of `<<` binary expressions.
fn collect_shl_operands<'a>(expr: &'a Expr, operands: &mut Vec<&'a Expr>) {
    if let Expr::Binary(BinOp::Shl, lhs, rhs) = expr {
        collect_shl_operands(lhs, operands);
        operands.push(rhs);
    } else {
        operands.push(expr);
    }
}

fn is_cout_expr(expr: &Expr) -> bool {
    matches!(expr, Expr::Ident(name) if name == "std::cout" || name == "cout")
}

fn is_endl_expr(expr: &Expr) -> bool {
    matches!(expr, Expr::Ident(name) if name == "std::endl" || name == "endl")
}

fn generate_expr(out: &mut String, expr: &Expr, _indent: usize) -> Result<()> {
    match expr {
        Expr::Literal(lit) => generate_literal_inline(out, lit),
        Expr::Ident(name) => out.push_str(name),
        Expr::Binary(op, lhs, rhs) => {
            // Detect std::cout << ... << std::endl patterns
            if *op == BinOp::Shl {
                let mut operands = Vec::new();
                collect_shl_operands(expr, &mut operands);
                if !operands.is_empty() && is_cout_expr(operands[0]) {
                    let has_endl = operands.len() > 1 && is_endl_expr(operands.last().unwrap());
                    let content = &operands[1..if has_endl { operands.len() - 1 } else { operands.len() }];
                    if content.is_empty() {
                        if has_endl {
                            out.push_str("println!()");
                        } else {
                            out.push_str("/* empty cout expression */");
                        }
                    } else {
                        let mut fmt_parts = Vec::new();
                        let mut args = Vec::new();
                        for operand in content {
                            match operand {
                                Expr::Literal(Literal::String(s)) => {
                                    fmt_parts.push(s.clone());
                                }
                                other => {
                                    fmt_parts.push("{}".to_string());
                                    args.push(other);
                                }
                            }
                        }
                        let fmt_str = fmt_parts.join("");
                        if has_endl {
                            out.push_str("println!(\"");
                        } else {
                            out.push_str("print!(\"");
                        }
                        out.push_str(&fmt_str);
                        out.push('\"');
                        for arg in args {
                            out.push_str(", ");
                            generate_expr(out, arg, _indent)?;
                        }
                        out.push(')');
                    }
                    return Ok(());
                }
            }
            out.push('(');
            generate_expr(out, lhs, _indent)?;
            out.push(' ');
            out.push_str(&op.to_string());
            out.push(' ');
            generate_expr(out, rhs, _indent)?;
            out.push(')');
        }
        Expr::Unary(op, inner) => {
            out.push_str(&op.to_string());
            generate_expr(out, inner, _indent)?;
        }
        Expr::Call(callee, args) => {
            // Handle method calls where callee is Field(obj, method)
            if let Expr::Field(obj, method) = callee.as_ref() {
                match method.as_str() {
                    "size" | "empty" | "front" | "back" if args.is_empty() => {
                        let rust_method = match method.as_str() {
                            "size" => "len",
                            "empty" => "is_empty",
                            other => other,
                        };
                        generate_expr(out, obj, _indent)?;
                        out.push('.');
                        out.push_str(rust_method);
                        out.push_str("()");
                        return Ok(());
                    }
                    "push_back" | "emplace_back" | "emplace" if !args.is_empty() => {
                        generate_expr(out, obj, _indent)?;
                        out.push_str(".push_back(");
                        for (i, arg) in args.iter().enumerate() {
                            if i > 0 {
                                out.push_str(", ");
                            }
                            generate_expr(out, arg, _indent)?;
                        }
                        out.push(')');
                        return Ok(());
                    }
                    "pop" if args.is_empty() => {
                        generate_expr(out, obj, _indent)?;
                        out.push_str(".pop_front()");
                        return Ok(());
                    }
                    _ => {}
                }
            }
            // Handle vector constructors
            if let Expr::Ident(name) = callee.as_ref() {
                if name == "vector" || name == "std::vector" {
                    match args.len() {
                        0 => {
                            out.push_str("Vec::new()");
                            return Ok(());
                        }
                        1 => {
                            out.push_str("Vec::with_capacity(");
                            generate_expr(out, &args[0], _indent)?;
                            out.push(')');
                            return Ok(());
                        }
                        2 => {
                            out.push_str("vec![");
                            generate_expr(out, &args[1], _indent)?;
                            out.push_str("; ");
                            generate_expr(out, &args[0], _indent)?;
                            out.push(']');
                            return Ok(());
                        }
                        _ => {}
                    }
                }
            }
            // Map std::make_unique<T>(...) -> Box::new(T::new(...))
            if let Expr::Ident(name) = callee.as_ref() {
                let base_name = name.split('<').next().unwrap_or(name);
                if base_name == "std::make_unique" || base_name == "make_unique" {
                    out.push_str("Box::new(");
                    // Extract template argument like "Point" from "std::make_unique<Point>"
                    let ty_arg = name.split('<').nth(1).and_then(|s| s.split('>').next());
                    if let Some(ty) = ty_arg {
                        out.push_str(ty);
                        out.push_str("::new(");
                        for (i, arg) in args.iter().enumerate() {
                            if i > 0 {
                                out.push_str(", ");
                            }
                            generate_expr(out, arg, _indent)?;
                        }
                        out.push(')');
                    } else {
                        for (i, arg) in args.iter().enumerate() {
                            if i > 0 {
                                out.push_str(", ");
                            }
                            generate_expr(out, arg, _indent)?;
                        }
                    }
                    out.push(')');
                    return Ok(());
                }
            }
            generate_expr(out, callee, _indent)?;
            out.push('(');
            for (i, arg) in args.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                generate_expr(out, arg, _indent)?;
            }
            out.push(')');
        }
        Expr::MethodCall(receiver, method, args) => {
            let rust_method = match method.as_str() {
                "size" => "len",
                "emplace_back" | "push_back" => "push",
                "front" => "front",
                "back" => "back",
                "pop" => "pop",
                "empty" => "is_empty",
                _ => method,
            };
            generate_expr(out, receiver, _indent)?;
            out.push('.');
            out.push_str(rust_method);
            out.push('(');
            for (i, arg) in args.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                generate_expr(out, arg, _indent)?;
            }
            out.push(')');
        }
        Expr::Field(obj, field) => {
            generate_expr(out, obj, _indent)?;
            out.push('.');
            out.push_str(field);
        }
        Expr::Index(arr, idx) => {
            generate_expr(out, arr, _indent)?;
            out.push('[');
            generate_expr(out, idx, _indent)?;
            out.push(']');
        }
        Expr::If(cond, then_branch, else_branch) => {
            out.push_str("if ");
            generate_expr(out, cond, _indent)?;
            out.push_str(" {\n");
            generate_block(out, then_branch, _indent + 1)?;
            out.push_str(&"    ".repeat(_indent));
            out.push('}');
            if let Some(else_b) = else_branch {
                out.push_str(" else {\n");
                generate_block(out, else_b, _indent + 1)?;
                out.push_str(&"    ".repeat(_indent));
                out.push('}');
            }
        }
        Expr::Match(scrutinee, arms) => {
            out.push_str("match ");
            generate_expr(out, scrutinee, _indent)?;
            out.push_str(" {\n");
            for arm in arms {
                out.push_str(&"    ".repeat(_indent + 1));
                generate_pattern_inline(out, &arm.pat)?;
                if let Some(guard) = &arm.guard {
                    out.push_str(" if ");
                    generate_expr(out, guard, _indent + 1)?;
                }
                out.push_str(" => ");
                generate_expr(out, &arm.body, _indent + 1)?;
                out.push_str(",\n");
            }
            out.push_str(&"    ".repeat(_indent));
            out.push('}');
        }
        Expr::While(cond, body) => {
            out.push_str("while ");
            generate_expr(out, cond, _indent)?;
            out.push_str(" {\n");
            generate_block(out, body, _indent + 1)?;
            out.push_str(&"    ".repeat(_indent));
            out.push('}');
        }
        Expr::For(head, body) => {
            out.push_str("for ");
            generate_pattern_inline(out, &head.pat)?;
            out.push_str(" in ");
            generate_expr(out, &head.expr, _indent)?;
            out.push_str(" {\n");
            generate_block(out, body, _indent + 1)?;
            out.push_str(&"    ".repeat(_indent));
            out.push('}');
        }
        Expr::Block(block) => {
            out.push_str("{\n");
            generate_block(out, block, _indent + 1)?;
            out.push_str(&"    ".repeat(_indent));
            out.push('}');
        }
        Expr::StructInit(name, fields) => {
            out.push_str(name);
            out.push_str(" {");
            for (i, (fname, fexpr)) in fields.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                out.push_str(fname);
                out.push_str(": ");
                generate_expr(out, fexpr, _indent)?;
            }
            out.push('}');
        }
        Expr::ArrayInit(elems) => {
            out.push('[');
            for (i, e) in elems.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                generate_expr(out, e, _indent)?;
            }
            out.push(']');
        }
        Expr::Tuple(elems) => {
            out.push('(');
            for (i, e) in elems.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                generate_expr(out, e, _indent)?;
            }
            out.push(')');
        }
        Expr::Break => out.push_str("break"),
        Expr::Continue => out.push_str("continue"),
        Expr::Closure(params, ret_ty, body) => {
            out.push('|');
            for (i, p) in params.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                out.push_str(&p.name);
                out.push_str(": ");
                generate_type_inline(out, &p.ty)?;
            }
            out.push('|');
            if let Some(ret) = ret_ty {
                out.push_str(" -> ");
                generate_type_inline(out, ret)?;
            }
            out.push_str(" {\n");
            generate_block(out, body, _indent + 1)?;
            out.push_str(&"    ".repeat(_indent));
            out.push('}');
        }
        Expr::TODO(msg) => {
            out.push_str("todo!(");
            out.push('"');
            out.push_str(msg);
            out.push_str("\"");
            out.push(')');
        }
    }
    Ok(())
}

fn generate_type(out: &mut String, ty: &Type) -> Result<()> {
    match ty {
        Type::Unit => out.push_str("()"),
        Type::Never => out.push_str("!"),
        Type::Infer => out.push_str("_"),
        Type::Named(name, args) => {
            let rust_name = map_cpp_type_to_rust(name);
            out.push_str(&rust_name);
            if !args.is_empty() {
                out.push('<');
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 {
                        out.push_str(", ");
                    }
                    generate_type_inline(out, arg)?;
                }
                out.push('>');
            }
        }
        Type::Ref(inner, mutability) => {
            out.push('&');
            if *mutability == Mutability::Mut {
                out.push_str("mut ");
            }
            generate_type_inline(out, inner)?;
        }
        Type::Ptr(inner, mutability) => {
            out.push('*');
            if *mutability == Mutability::Mut {
                out.push_str("mut ");
            } else {
                out.push_str("const ");
            }
            generate_type_inline(out, inner)?;
        }
        Type::Array(inner, len) => {
            out.push('[');
            generate_type_inline(out, inner)?;
            if let Some(n) = len {
                out.push_str("; ");
                out.push_str(&n.to_string());
            }
            out.push(']');
        }
        Type::Tuple(elems) => {
            out.push('(');
            for (i, e) in elems.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                generate_type_inline(out, e)?;
            }
            out.push(')');
        }
        Type::Function(args, ret) => {
            out.push_str("fn(");
            for (i, a) in args.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                generate_type_inline(out, a)?;
            }
            out.push(')');
            generate_type_inline(out, ret)?;
        }
        Type::Slice(inner) => {
            out.push('[');
            generate_type_inline(out, inner)?;
            out.push(']');
        }
        Type::TODO(msg) => {
            out.push_str("/* TODO type: ");
            out.push_str(msg);
            out.push_str(" */ ()");
        }
    }
    Ok(())
}

fn generate_type_inline(out: &mut String, ty: &Type) -> Result<()> {
    generate_type(out, ty)
}

fn map_cpp_type_to_rust(name: &str) -> String {
    match name {
        "std::vector" | "vector" => "Vec".to_string(),
        "std::unique_ptr" | "unique_ptr" => "Box".to_string(),
        "std::shared_ptr" | "shared_ptr" => "Rc".to_string(), // TODO: choose Rc/Arc based on Send/Sync needs
        "std::string" | "string" => "String".to_string(),
        "std::optional" | "optional" => "Option".to_string(),
        "std::expected" | "expected" => "Result".to_string(),
        "std::unordered_map" | "unordered_map" => "HashMap".to_string(),
        "std::unordered_set" | "unordered_set" => "HashSet".to_string(),
        "std::queue" | "queue" | "Queue" => "std::collections::VecDeque".to_string(),
        "std::map" | "map" => "BTreeMap".to_string(),
        "std::set" | "set" => "BTreeSet".to_string(),
        "void" => "()".to_string(),
        "bool" => "bool".to_string(),
        "char" => "char".to_string(),
        "wchar_t" => "char".to_string(),
        "char8_t" => "u8".to_string(),
        "char16_t" => "u16".to_string(),
        "char32_t" => "char".to_string(),
        "int8_t" => "i8".to_string(),
        "int16_t" => "i16".to_string(),
        "int32_t" => "i32".to_string(),
        "int64_t" => "i64".to_string(),
        "uint8_t" => "u8".to_string(),
        "uint16_t" => "u16".to_string(),
        "uint32_t" => "u32".to_string(),
        "uint64_t" => "u64".to_string(),
        "size_t" => "usize".to_string(),
        "ptrdiff_t" => "isize".to_string(),
        "float" => "f32".to_string(),
        "double" => "f64".to_string(),
        "int" => "i32".to_string(),
        "long" => "i64".to_string(),
        "short" => "i16".to_string(),
        other => other.to_string(), // fallback
    }
}

fn generate_literal_inline(out: &mut String, lit: &Literal) {
    match lit {
        Literal::Int(s) => out.push_str(s),
        Literal::Float(s) => out.push_str(s),
        Literal::String(s) => {
            out.push('"');
            out.push_str(s);
            out.push('"');
        }
        Literal::Char(c) => {
            out.push('\'');
            out.push(*c);
            out.push('\'');
        }
        Literal::Bool(b) => out.push_str(if *b { "true" } else { "false" }),
    }
}

fn generate_pattern_inline(out: &mut String, pat: &Pattern) -> Result<()> {
    match pat {
        Pattern::Wild => out.push('_'),
        Pattern::Literal(lit) => generate_literal_inline(out, lit),
        Pattern::Ident(name) => out.push_str(name),
        Pattern::Struct(name, fields) => {
            out.push_str(name);
            out.push_str(" {");
            for (i, (fname, fpat)) in fields.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                out.push_str(fname);
                out.push_str(": ");
                generate_pattern_inline(out, fpat)?;
            }
            out.push('}');
        }
        Pattern::Tuple(pats) => {
            out.push('(');
            for (i, p) in pats.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                generate_pattern_inline(out, p)?;
            }
            out.push(')');
        }
        Pattern::Array(pats) => {
            out.push('[');
            for (i, p) in pats.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                generate_pattern_inline(out, p)?;
            }
            out.push(']');
        }
        Pattern::Ref(p) => {
            out.push_str("ref ");
            generate_pattern_inline(out, p)?;
        }
        Pattern::Mut(p) => {
            out.push_str("mut ");
            generate_pattern_inline(out, p)?;
        }
        Pattern::Or(pats) => {
            for (i, p) in pats.iter().enumerate() {
                if i > 0 {
                    out.push_str(" | ");
                }
                generate_pattern_inline(out, p)?;
            }
        }
    }
    Ok(())
}
